### ISSUE TITLE
Problem running docker-backup when docker daemon runs in host mode

### ISSUE THREAD

**Issue by mikedolx** [discordianfish/docker-backup#8]
Hi,

I'm currently trying to run a volume backup with docker-backup on my docker host. The docker daemon runs in host mode meaning it accepts remote connections on a custom tcp port (-H tcp://0.0.0.0:30000) but the standard option via unix file is also available (-H unix:// ). 

When i try to run the docker-backup with the the following options 

    docker-backup --addr localhost:30000 --proto tcp store /path/to/my/archive.tar.gz mycontainer

or 

    docker-backup --addr /var/run/docker.sock --proto unix store /path/to/my/archive.tar.gz mycontainer

i get the error message 
    
    Storing mycontainer's volume container as /path/to/my/archive.tar.gz
    Couldn't find data container

Am i missing something? Any help would be appreciated.

Thanks

Michael

**Comment by discordianfish** [comment]
This tool assumes that you have a dedicated 'volume container' you use with `--volumes-from` flag, which was best practice back in the days.
I probably should archive this project since I'm not using it anymore. In context of something like Kubernetes you should use volume snapshots etc for backups anyways.
